version: '3'
services:
  eureka:
    image: "eureka-server"
    container_name: "eureka-server"
    restart: always
  payment:
    image: "payment-service"
    depends_on:
      - eureka
    ports:
      - "8002:8002"
  client:
    image: "client-service"
    depends_on:
      - eureka
    ports:
      - "8001:8001"
  cashback:
    image: "cashback-service"
    depends_on:
      - eureka
    ports:
      - "8003:8003"



